version: '3'

services:
  server:
    image: nats:2.6.4-scratch
    ports:
      - 127.0.0.1:4222:4222
      - 127.0.0.1:4223:4223
      - 127.0.0.1:8222:8222
    environment:
      - NATS_TOKEN_ADMIN=${ADMIN_TOKEN}
      - NATS_TOKEN_MANAGER=${MANAGER_TOKEN}
      - NATS_TOKEN_COLLECTOR=${COLLECTOR_TOKEN}
    volumes:
      - ./nats-server.conf:/nats-server.conf
    command: -js -c /nats-server.conf
  # transport:
  #   build:
  #     dockerfile: docker/Dockerfile
  #     context: .
  #   env_file:
  #   - .env.local
  #   environment:
  #     - PORT
  #     - NODE_ENV
  #     - VUE_APP_MATOMO_URL
  #     - VUE_APP_MATOMO_SITE
  #     - VUE_APP_TITLE
  #   restart: always
  #   ports:
  #     - 8080:8080
